[tools]
java = "temurin-17.0.19+10"
gradle = "8.9"

[env]
ANDROID_HOME = "{{ env.HOME }}/Android/Sdk"
ANDROID_SDK_ROOT = "{{ env.HOME }}/Android/Sdk"
_.path = [
  "{{ env.HOME }}/Android/Sdk/cmdline-tools/latest/bin",
  "{{ env.HOME }}/Android/Sdk/platform-tools",
]
